-- Prevent duplicate active food names per user without changing RLS or grants.
-- Names are normalized the same way as the app: trim whitespace and compare
-- case-insensitively. Soft-deleted foods do not block recreating a name.

create unique index if not exists foods_user_active_name_unique_idx
  on public.foods (user_id, lower(btrim(name)))
  where deleted_at is null;

revoke all on table public.foods from anon, authenticated;

grant select, insert, update on table public.foods to authenticated;

-- No sequence privileges are granted: foods uses UUID primary keys generated by
-- extensions.gen_random_uuid(), so authenticated users do not need sequences.
